export const blogs = [
  {
    slug: '6-things-to-know-about-loan-against-mutual-funds',
    img: 'https://cdn.prod.website-files.com/68d7e7065b4cad954e1c911b/68e36e1a0c2d1510981e128e_8.png',
    title: '6 Things to Know About Loan Against Mutual Funds',
    date: '15 APR 24',
    read: '6 MIN READ',
    desc: 'Get fast access to cash without selling your investments with loan against mutual funds',
    content: [
      { type: 'p', text: 'In times of financial need, the conventional approach is to sell off assets, but there\'s an alternative that doesn\'t require unwinding your investments: leveraging your Mutual Fund.' },
      { type: 'p', text: 'By securing a Loan Against Mutual Funds from a financial institution or an NBFC, you\'re essentially tapping into the worth of your portfolio without having to liquidate it. Here are six essential things you should know about this type of loan.' },
      { type: 'h2', text: '1. What Is a Loan Against Mutual Funds?' },
      { type: 'p', text: 'A Loan Against Mutual Funds (LAMF) is a secured loan where your mutual fund units are used as collateral. Instead of selling your units, you pledge them to a lender who then provides you with a loan amount based on the current Net Asset Value (NAV) of those units.' },
      { type: 'h2', text: '2. How Much Can You Borrow?' },
      { type: 'p', text: 'The loan amount depends on the type of mutual fund and its current value. Typically, you can borrow up to 50% of the NAV for equity funds and up to 80% for debt funds. This ratio is known as the Loan-to-Value (LTV) ratio.' },
      { type: 'h2', text: '3. Your Investments Keep Growing' },
      { type: 'p', text: 'One of the biggest advantages: your pledged units remain invested. They continue to earn returns — dividends and capital appreciation — even while they serve as collateral. You only lose access if you default.' },
      { type: 'h2', text: '4. Interest Rates Are Competitive' },
      { type: 'p', text: 'LAMF interest rates typically range from 9% to 13% per annum, which is significantly lower than personal loans (14–24%) or credit cards (36–42%). This makes it an efficient borrowing option for those with sizeable mutual fund portfolios.' },
      { type: 'h2', text: '5. Quick Disbursement' },
      { type: 'p', text: 'Since the loan is secured and KYC is already done for mutual fund investors, disbursement can happen within hours to a day. Platforms like Finsire leverage digital lien-marking with CAMS and KFintech for near-instant processing.' },
      { type: 'h2', text: '6. Flexible Repayment Options' },
      { type: 'p', text: 'Most LAMF products offer an overdraft facility, meaning you only pay interest on the amount you actually use. You can repay the principal anytime, giving you maximum flexibility without prepayment penalties.' },
      { type: 'p', text: 'Ready to unlock the value of your portfolio without selling a single unit? Explore how Finsire makes it simple, fast, and fully digital.' },
    ],
  },
  {
    slug: 'myths-and-facts-about-loan-against-mutual-fund',
    img: 'https://cdn.prod.website-files.com/68d7e7065b4cad954e1c911b/68e36c731c1656ec7770091c_7.png',
    title: 'Myths and Facts About Loan Against Mutual Fund',
    date: '11 JUN 24',
    read: '3 MIN READ',
    desc: 'Unlock the potential of your investments with our guide to loans against mutual funds',
    content: [
      { type: 'p', text: 'Loan Against Mutual Funds is one of the most underused financial tools in India — largely because of widespread misconceptions. Let\'s bust the most common myths.' },
      { type: 'h2', text: 'Myth 1: You Lose Ownership of Your Funds' },
      { type: 'p', text: 'Fact: You don\'t. Pledging is not the same as selling. You remain the beneficial owner. The lender only gets a lien — meaning they can sell the units only if you default on your loan.' },
      { type: 'h2', text: 'Myth 2: The Process Is Complicated and Slow' },
      { type: 'p', text: 'Fact: Modern platforms like Finsire complete the entire process digitally — lien marking, KYC, and disbursement — in as little as 5 minutes. No branch visits, no mountains of paperwork.' },
      { type: 'h2', text: 'Myth 3: Returns Stop Once You Pledge' },
      { type: 'p', text: 'Fact: Your units continue to earn NAV-based appreciation and dividends throughout the loan period. The pledge doesn\'t interrupt the performance of your portfolio.' },
      { type: 'h2', text: 'Myth 4: It\'s Only for Large Investors' },
      { type: 'p', text: 'Fact: You can get a loan against mutual funds starting from as low as ₹10,000. The loan amount scales with your portfolio size, making it accessible for both small and large investors.' },
      { type: 'h2', text: 'Myth 5: Interest Rates Are High' },
      { type: 'p', text: 'Fact: Rates typically start at 9–10.5% p.a., which is among the lowest in the personal lending space — far below credit cards or personal loans.' },
      { type: 'p', text: 'Don\'t let myths keep you from a powerful financial tool. With the right platform, a Loan Against Mutual Funds is simple, fast, and cost-effective.' },
    ],
  },
  {
    slug: 'managing-loan-against-mutual-funds-amid-market-volatility',
    img: 'https://cdn.prod.website-files.com/68d7e7065b4cad954e1c911b/68e36e41914d80d53fc87d05_6.png',
    title: 'Managing Loan Against Mutual Funds Amid Market Volatility',
    date: '19 JUN 24',
    read: '3 MIN READ',
    desc: 'Discover how market volatility impacts loan against mutual funds and strategies to manage risk.',
    content: [
      { type: 'p', text: 'Market volatility is an inherent part of investing. When you have a Loan Against Mutual Funds (LAMF), market swings can directly impact your collateral value — and therefore your loan eligibility.' },
      { type: 'h2', text: 'Understanding the Margin Call Risk' },
      { type: 'p', text: 'When markets fall sharply, the NAV of your pledged funds drops. If the value falls below the required LTV threshold, your lender may issue a "margin call" — asking you to either repay part of the loan or pledge additional units to restore the ratio.' },
      { type: 'h2', text: 'Strategy 1: Maintain a Buffer' },
      { type: 'p', text: 'Don\'t borrow the maximum permissible amount. Keep your LTV at 60–70% of the allowed limit. This buffer gives you room to absorb market dips without triggering a margin call.' },
      { type: 'h2', text: 'Strategy 2: Prefer Debt Fund Collateral' },
      { type: 'p', text: 'Debt mutual funds have lower volatility compared to equity funds. If market swings concern you, consider pledging debt funds — they also attract higher LTV ratios (up to 80%), giving you more borrowing power with less risk.' },
      { type: 'h2', text: 'Strategy 3: Monitor Your Portfolio' },
      { type: 'p', text: 'Stay informed. Platforms like Finsire send alerts when your collateral value changes significantly, giving you time to act before a margin call is triggered.' },
      { type: 'h2', text: 'Strategy 4: Keep Liquid Reserves' },
      { type: 'p', text: 'Always maintain some liquid savings to respond quickly to margin calls. This prevents forced liquidation of your pledged funds at unfavorable market prices.' },
      { type: 'p', text: 'Volatility is manageable when you borrow smartly. Plan your LAMF strategy with a cushion, and let your portfolio work for you even in choppy markets.' },
    ],
  },
  {
    slug: 'loan-against-mutual-funds-choosing-the-right-mutual-funds-for-collateral',
    img: 'https://cdn.prod.website-files.com/68d7e7065b4cad954e1c911b/68e36e6868e2a733fabc398e_5.png',
    title: 'Loan Against Mutual Funds: Choosing the Right Mutual Funds for Collateral',
    date: '26 JUN 24',
    read: '4 MIN READ',
    desc: 'An approach to selecting mutual funds for collateral purposes.',
    content: [
      { type: 'p', text: 'Not all mutual funds are treated equally when it comes to pledging as collateral. The type of fund you pledge determines the loan amount you can get, the risk you carry, and the lender\'s comfort with your application.' },
      { type: 'h2', text: 'Equity vs Debt Funds: The LTV Difference' },
      { type: 'p', text: 'Equity mutual funds — including large-cap, mid-cap, and flexi-cap funds — typically attract an LTV of 40–50%. Debt funds, being more stable, attract 70–80% LTV. This means pledging ₹10 lakh in a debt fund can net you up to ₹8 lakh, versus ₹5 lakh for an equity fund.' },
      { type: 'h2', text: 'Prefer Large-Cap and Index Funds for Equity Pledges' },
      { type: 'p', text: 'If you\'re pledging equity funds, stick to large-cap or index funds. They have lower volatility and are more likely to be accepted by lenders. Mid-cap and small-cap funds may be rejected or attract very low LTV ratios.' },
      { type: 'h2', text: 'Check the AMFI and Lender\'s Approved List' },
      { type: 'p', text: 'Lenders maintain an approved list of mutual funds eligible for pledging. Funds that are illiquid, thematic, or sectoral may not qualify. Always verify with your lender before assuming a fund is eligible.' },
      { type: 'h2', text: 'Diversify Your Collateral Pool' },
      { type: 'p', text: 'Don\'t put all your pledgeable eggs in one basket. A mix of debt and large-cap equity funds as collateral gives you better LTV, lower margin-call risk, and more negotiating power with lenders.' },
      { type: 'h2', text: 'Keep High-Growth Funds Free' },
      { type: 'p', text: 'If you hold high-conviction, high-growth funds in your portfolio, consider pledging more stable funds instead. This way, your growth engines remain unencumbered and can be freely redeemed if needed.' },
      { type: 'p', text: 'Choosing the right collateral isn\'t just about eligibility — it\'s a strategic decision that affects your cost, risk, and flexibility. Plan it wisely.' },
    ],
  },
  {
    slug: 'understanding-the-terms-of-loan-against-mutual-funds',
    img: 'https://cdn.prod.website-files.com/68d7e7065b4cad954e1c911b/68e36e8a885561bc786d637b_4.png',
    title: 'Understanding the Terms of Loan Against Mutual Funds',
    date: '25 JUL 24',
    read: '4 MIN READ',
    desc: 'Explore the essentials of loan terms and interest rates when borrowing against mutual funds.',
    content: [
      { type: 'p', text: 'Before you sign up for a Loan Against Mutual Funds, it\'s critical to understand the key terms and conditions that govern the product. Here\'s a breakdown of what to look for.' },
      { type: 'h2', text: 'Loan-to-Value (LTV) Ratio' },
      { type: 'p', text: 'The LTV ratio determines how much you can borrow relative to the market value of your pledged funds. For equity funds, it\'s typically 50%; for debt funds, up to 80%. The LTV may change if your fund\'s NAV fluctuates significantly.' },
      { type: 'h2', text: 'Interest Rate Structure' },
      { type: 'p', text: 'LAMF products are usually offered as an overdraft with a floating interest rate linked to the RBI repo rate or the lender\'s internal benchmark. Rates typically range from 9% to 13% p.a. Some lenders charge interest only on the amount utilized, not the sanctioned limit.' },
      { type: 'h2', text: 'Tenure and Renewal' },
      { type: 'p', text: 'Most LAMF products come with a 12-month tenure, renewable annually. Some platforms offer 24 or 36-month tenures. At renewal, the lender reassesses your portfolio value and may revise the sanctioned limit accordingly.' },
      { type: 'h2', text: 'Processing Fees and Other Charges' },
      { type: 'p', text: 'Watch out for processing fees (typically 0.5–1% of the loan amount), stamp duty, lien marking charges, and penal interest for delays. Always read the full schedule of charges before signing.' },
      { type: 'h2', text: 'Prepayment and Foreclosure' },
      { type: 'p', text: 'Most LAMF overdraft facilities allow prepayment without penalty. However, term loan variants may have a lock-in period. Confirm the prepayment terms upfront so you know the exit cost if you want to close the loan early.' },
      { type: 'p', text: 'Understanding these terms helps you compare offers effectively and choose the right product for your financial situation.' },
    ],
  },
  {
    slug: 'loan-against-mutual-funds-sip-explained-tap-liquidity-while-staying-invested',
    img: 'https://cdn.prod.website-files.com/68d7e7065b4cad954e1c911b/68e36f04dfa20e2c977bdfa1_3.png',
    title: 'Loan Against Mutual Funds SIP Explained: Tap Liquidity While Staying Invested',
    date: '20 JAN 25',
    read: '4 MIN READ',
    desc: 'Discover how to unlock liquidity from your SIP holdings without breaking your investment discipline.',
    content: [
      { type: 'p', text: 'SIPs (Systematic Investment Plans) are the backbone of disciplined wealth creation for millions of Indians. But what happens when you face a sudden cash crunch? You don\'t have to stop or redeem your SIP — you can borrow against it.' },
      { type: 'h2', text: 'Can You Pledge SIP Units?' },
      { type: 'p', text: 'Yes. Every SIP instalment creates mutual fund units in your name, and these units can be pledged to avail a loan — just like lump-sum investments. The pledging is done unit by unit based on the current NAV.' },
      { type: 'h2', text: 'How It Works' },
      { type: 'p', text: 'You select which units to pledge (usually based on age or fund type), the lender places a lien on those units via CAMS or KFintech, and you receive a loan against their value. Your SIP continues uninterrupted — new units added each month are not pledged unless you choose to do so.' },
      { type: 'h2', text: 'Benefits of Borrowing Against SIP Units' },
      { type: 'p', text: 'You avoid breaking your investment streak. Long-term SIP investors benefit from rupee cost averaging and compounding — redeeming early can seriously hurt these gains. A loan lets you access funds without disrupting this engine.' },
      { type: 'h2', text: 'Tax Implications' },
      { type: 'p', text: 'Taking a loan against mutual funds is not a taxable event. Unlike redemption, which may attract short-term or long-term capital gains tax, a pledge and loan does not trigger any tax liability — another significant advantage.' },
      { type: 'h2', text: 'Things to Watch Out For' },
      { type: 'p', text: 'If the NAV of your pledged SIP units falls significantly, you may face a margin call. Also, units bought within 1–3 years may still be within the lock-in for ELSS or subject to exit loads if the lender needs to sell them upon default.' },
      { type: 'p', text: 'For the disciplined SIP investor, pledging is a smarter alternative to breaking a goal-based investment. Stay invested, stay liquid.' },
    ],
  },
  {
    slug: 'loan-against-mutual-funds-which-makes-more-sense-term-loan-or-overdraft',
    img: 'https://cdn.prod.website-files.com/68d7e7065b4cad954e1c911b/68e36f1f878888e2da75b191_2.png',
    title: 'Loan Against Mutual Funds: Which Makes More Sense — Term Loan or Overdraft?',
    date: '20 JAN 25',
    read: '4 MIN READ',
    desc: 'Discover how to leverage your mutual fund investments for quick financing.',
    content: [
      { type: 'p', text: 'When you apply for a Loan Against Mutual Funds, most lenders offer two structures: a Term Loan or an Overdraft (OD) facility. Understanding the difference can save you thousands in interest costs.' },
      { type: 'h2', text: 'Term Loan: Fixed Amount, Fixed Schedule' },
      { type: 'p', text: 'A term loan disburses a fixed amount upfront, and you repay it in equal monthly installments (EMIs) over a set tenure. Interest is charged on the full outstanding principal. This suits borrowers who need a lump sum for a specific purpose — like a home down payment or medical emergency.' },
      { type: 'h2', text: 'Overdraft: Flexible Draw-Down, Pay Only for What You Use' },
      { type: 'p', text: 'An overdraft facility gives you a sanctioned credit limit. You draw and repay as needed. Interest is charged only on the amount actually utilized, not the full limit. This makes it far more cost-efficient for working capital or irregular cash needs.' },
      { type: 'h2', text: 'Cost Comparison' },
      { type: 'p', text: 'Example: You have a ₹5 lakh limit. With a term loan, you pay interest on ₹5 lakh from day one. With an OD, if you only draw ₹2 lakh, you pay interest only on ₹2 lakh. Over a year, this difference can be ₹30,000–₹40,000 in savings.' },
      { type: 'h2', text: 'Which Should You Choose?' },
      { type: 'p', text: 'Choose a term loan if you need a defined sum for a one-time expense and prefer predictable EMIs. Choose an overdraft if your cash needs are uncertain or periodic — you\'ll save significantly on interest and have maximum flexibility.' },
      { type: 'p', text: 'Most Finsire borrowers find the overdraft structure more aligned with how they actually use borrowed funds. Start with OD, switch to term if your needs evolve.' },
    ],
  },
  {
    slug: 'loan-against-mutual-funds-5-times-its-the-best-option',
    img: 'https://cdn.prod.website-files.com/68d7e7065b4cad954e1c911b/68e36f42d2184c53069dab2d_1.png',
    title: "Loan Against Mutual Funds: 5 Times It's the Best Option",
    date: '21 JAN 25',
    read: '4 MIN READ',
    desc: 'Explore 5 situations where a loan against mutual funds helps you meet financial needs efficiently.',
    content: [
      { type: 'p', text: 'There are moments in life when you need cash fast but don\'t want to derail your long-term financial plan. A Loan Against Mutual Funds is purpose-built for exactly these moments. Here are five situations where it\'s the smartest choice.' },
      { type: 'h2', text: '1. Medical Emergencies' },
      { type: 'p', text: 'Unexpected hospitalization or surgery can demand lakhs within hours. A LAMF can be disbursed in minutes digitally — far faster than a personal loan or liquidating a fixed deposit. And you pay back only when you can, with interest only on what you use.' },
      { type: 'h2', text: '2. Business Working Capital' },
      { type: 'p', text: 'Small business owners often face temporary cash gaps between receivables and payables. Instead of a business loan with high rates and collateral requirements, pledging personal mutual funds offers cheaper, faster capital without involving the business\'s assets.' },
      { type: 'h2', text: '3. Bridging a Home Purchase' },
      { type: 'p', text: 'Between booking a property and the bank disbursing your home loan, there\'s often a gap of weeks. A LAMF bridges this gap without forcing you to sell investments at the wrong time.' },
      { type: 'h2', text: '4. Educational Expenses' },
      { type: 'p', text: 'If your child\'s admission fee or semester payment is due and your FD hasn\'t matured, pledging your mutual fund units is far cheaper than breaking the FD early or taking an education loan at high interest.' },
      { type: 'h2', text: '5. Avoiding a Bad Sale' },
      { type: 'p', text: 'Markets can be down when you need cash most. Selling equity funds at a loss defeats the purpose of long-term investing. A LAMF lets you hold and wait for recovery while still accessing the funds you need today.' },
      { type: 'p', text: 'The beauty of LAMF is its versatility. Whether it\'s planned or unplanned, short-term or medium-term, it\'s a Swiss army knife in your financial toolkit.' },
    ],
  },
  {
    slug: 'mastering-mutual-fund-performance-essential-tools-simplified',
    img: 'https://cdn.prod.website-files.com/68d7e7065b4cad954e1c911b/68e370b481835790038869b7_9.png',
    title: 'Mastering Mutual Fund Performance: Essential Tools Simplified',
    date: '15 JUL 24',
    read: '3 MIN READ',
    desc: 'Discover simple, practical tools to understand and evaluate mutual fund performance.',
    content: [
      { type: 'p', text: 'Investing in mutual funds is only half the battle. The other half is understanding whether your investments are performing well. Here are the essential tools and metrics every investor should know.' },
      { type: 'h2', text: 'NAV: The Baseline' },
      { type: 'p', text: 'Net Asset Value (NAV) is the per-unit market value of a fund\'s assets minus liabilities. While NAV alone doesn\'t tell you if a fund is cheap or expensive, tracking its movement over time gives you a clear picture of performance.' },
      { type: 'h2', text: 'CAGR: Your True Returns' },
      { type: 'p', text: 'Compound Annual Growth Rate (CAGR) is the most accurate way to measure long-term returns. It accounts for compounding and smooths out yearly volatility. Always compare a fund\'s CAGR against its benchmark and category average.' },
      { type: 'h2', text: 'Sharpe Ratio: Risk-Adjusted Returns' },
      { type: 'p', text: 'A high return is great — but not if it came with extreme risk. The Sharpe Ratio measures how much return you\'re getting per unit of risk. A ratio above 1 is generally considered good. Compare Sharpe ratios across funds in the same category.' },
      { type: 'h2', text: 'Alpha and Beta' },
      { type: 'p', text: 'Alpha measures a fund manager\'s ability to beat the benchmark. Positive alpha means the fund outperformed. Beta measures how sensitive the fund is to market movements. A beta of 1 means it moves in lockstep with the market; less than 1 means it\'s more stable.' },
      { type: 'h2', text: 'Using MF Central and RTA Portals' },
      { type: 'p', text: 'MF Central (mfcentral.com), CAMS, and KFintech portals give you consolidated views of your entire mutual fund portfolio across fund houses. These are free to use and essential for tracking performance accurately.' },
      { type: 'p', text: 'Mastering these tools doesn\'t require a finance degree. Once you know what to look at, evaluating your portfolio becomes a 15-minute monthly exercise.' },
    ],
  },
];
